version: '2'
services:
  bitstar:
    image: bitstarcoin/linux-node:latest
    restart: always
    networks:
      - bridge
    ports:
      - 19534:19534
    volumes:
      - bitstarcoin:/home/bitstarcoin/
volumes:
  bitstarcoin:
    name: bitstarcoin
    driver: local
